export interface TemplateItem {
  description: string;
  unit: string;
  quantity: number;
  rate: number;
  notes?: string;
}

export interface QuotationTemplate {
  id: string;
  title: string;
  category: string;
  description: string;
  defaultTaxRate: number;
  paymentTerms: string;
  termsAndConditions: string;
  notes: string;
  items: TemplateItem[];
}

export const QUOTATION_TEMPLATES: QuotationTemplate[] = [
  {
    id: 'RESIDENTIAL_CONSTRUCTION',
    title: 'Residential Turnkey Construction Contract (G+1/G+2)',
    category: 'Turnkey Civil',
    description: 'Complete end-to-end residential building construction including foundation, RCC structure, masonry, plaster, flooring, and basic finishing.',
    defaultTaxRate: 18,
    paymentTerms: '• 20% Advance on agreement\n• 20% Upon completion of plinth beam\n• 20% Upon casting of ground floor slab\n• 20% Upon casting of first floor slab & brickwork\n• 15% Upon completion of plaster & flooring\n• 5% Final handover',
    termsAndConditions: '1. Electricity and water for construction shall be provided by the client free of charge at site.\n2. Work will be executed strictly in accordance with approved architectural drawings.\n3. Any extra items outside the BOQ scope will be charged extra with prior written approval.\n4. Material rates are based on current market indices; escalation beyond 5% will be borne by client.\n5. Standard defect liability period is 12 months from final handover.',
    notes: 'Rates include shuttering, scaffolding, labour, materials, equipment, and structural supervision.',
    items: [
      { description: 'Earthwork excavation in all types of soil for foundation trenches up to 6ft depth including refilling & compaction', unit: 'cum', quantity: 180, rate: 280, notes: 'Includes trench safety' },
      { description: 'Providing and laying Plain Cement Concrete (PCC 1:4:8) with 40mm metal in foundation base (100mm thick)', unit: 'cum', quantity: 35, rate: 4200, notes: 'M10 equivalent' },
      { description: 'Reinforced Cement Concrete (RCC M25) for footings, pedestal columns, and plinth beams with shuttering & steel tying', unit: 'cum', quantity: 50, rate: 8500, notes: 'Fe550D TMT bars' },
      { description: 'RCC M25 grade for columns, grade beams, lintels, and chajjas with steel scaffolding & formwork', unit: 'cum', quantity: 45, rate: 9200, notes: 'Vibrated finish' },
      { description: 'RCC M25 grade roof slab casting (125mm thick) including centering, shuttering, props, and mechanized pump pouring', unit: 'sq.ft.', quantity: 2400, rate: 380, notes: 'Double mesh reinforcement' },
      { description: '9" thick Red Clay Brick / AAC block masonry in cement mortar 1:6 for external load-bearing walls', unit: 'sq.ft.', quantity: 4200, rate: 145, notes: 'Includes curing' },
      { description: '4.5" thick partition wall masonry in cement mortar 1:4 with 6mm MS tie bars at every 3rd course', unit: 'sq.ft.', quantity: 2800, rate: 95, notes: 'Partition walls' },
      { description: '12mm thick internal smooth plaster in cement mortar 1:4 with sponge / neeru smooth coat finish', unit: 'sq.ft.', quantity: 9500, rate: 48, notes: 'Ready for putty' },
      { description: '20mm thick external double-coat sand-faced plaster with waterproof compound (Dr. Fixit)', unit: 'sq.ft.', quantity: 4800, rate: 72, notes: 'Waterproof coating' },
      { description: 'Vitrified tile flooring (4ft x 2ft) double-charged with cement mortar bed and epoxy joint filling', unit: 'sq.ft.', quantity: 2200, rate: 165, notes: 'Kajaria / Somany brand' },
    ],
  },
  {
    id: 'RCC_STRUCTURE',
    title: 'RCC Structural Framing & Slab Casting Package',
    category: 'Structural',
    description: 'Specialized structural contract focusing on heavy column footing, shear walls, beams, and high-strength concrete slab casting.',
    defaultTaxRate: 18,
    paymentTerms: '• 25% Advance with work order\n• 35% After completion of footing & columns up to plinth\n• 30% After slab shuttering, steel binding & pouring\n• 10% After de-shuttering & cube test validation',
    termsAndConditions: '1. RMC concrete will be sourced from approved batching plants.\n2. Steel testing certificates (Fe550D) will be submitted before bar bending.\n3. Cube test results (7 days and 28 days) will be provided for all concrete pours.',
    notes: 'Structural engineer inspection is mandatory prior to each slab pour.',
    items: [
      { description: 'Machine excavation in hard murrum/rock for column pits with hydraulic breaker', unit: 'cum', quantity: 120, rate: 450 },
      { description: 'M15 grade PCC bed for isolated footings (150mm depth)', unit: 'cum', quantity: 25, rate: 4800 },
      { description: 'M30 Design Mix Concrete for columns and lift shear walls with self-compacting properties', unit: 'cum', quantity: 65, rate: 9800 },
      { description: 'Plywood formwork & steel props system for beams and suspended floor slabs', unit: 'sq.ft.', quantity: 5000, rate: 85 },
      { description: 'Fabrication, cutting, bending, and placing Fe550D TMT reinforcement steel', unit: 'ton', quantity: 14, rate: 78000 },
      { description: 'RMC M25 pouring with mobile boom pump including needle vibrators and power trowel finish', unit: 'cum', quantity: 85, rate: 5800 },
    ],
  },
  {
    id: 'COMMERCIAL_INTERIOR',
    title: 'Commercial Corporate Office Fit-Out & Interior',
    category: 'Interior',
    description: 'Turnkey interior contract for corporate IT parks, offices, retail spaces including partitions, false ceiling, and acoustic finishing.',
    defaultTaxRate: 18,
    paymentTerms: '• 30% Mobilization advance\n• 30% After framework & conduit installation\n• 30% After ceiling, flooring & glazing fixing\n• 10% On snag clearance and final handover',
    termsAndConditions: '1. Work permitted during evening / night hours in commercial premises.\n2. Fire-retardant materials utilized for all partition frameworks.\n3. Noise-inducing work to be scheduled as per building guidelines.',
    notes: 'All items comply with NBC and local fire safety regulations.',
    items: [
      { description: '100mm Gypsum dry wall partition with GI studs, 12.5mm moisture-resistant boards, and rockwool sound insulation', unit: 'sq.ft.', quantity: 1800, rate: 220 },
      { description: '12mm Toughened glass partition with slimline black powder-coated aluminium profiles and dorma fittings', unit: 'sq.ft.', quantity: 650, rate: 480 },
      { description: 'Armstrong / Gyproc mineral fiber acoustic grid false ceiling (600x600mm) with silhouette grid', unit: 'sq.ft.', quantity: 3200, rate: 145 },
      { description: 'Heavy commercial nylon loop carpet tile flooring with 5mm cushion backing and adhesive installation', unit: 'sq.ft.', quantity: 2800, rate: 195 },
      { description: 'Concealed CAT6 data cabling, server rack point terminations, and 16A workstation power outlets', unit: 'nos', quantity: 45, rate: 2400 },
      { description: 'Acrylic emulsion paint on partition walls with 2 coats putty and anti-fungal primer', unit: 'sq.ft.', quantity: 5500, rate: 38 },
    ],
  },
  {
    id: 'VILLA_GREY_STRUCTURE',
    title: 'Villa & Luxury Bungalow Grey Structure Work',
    category: 'Civil',
    description: 'Civil core structure for luxury villas covering boundary, underground water tank, septic tank, and architectural cantilevers.',
    defaultTaxRate: 18,
    paymentTerms: '• 20% Initial mobilization\n• 25% Completion of plinth and underground sump\n• 30% Ground & First floor slab structure\n• 25% Parapet, septic tank, and boundary envelope',
    termsAndConditions: '1. Waterproofing admixture added to all foundation and water tank concrete.\n2. Precision shuttering ensures fair-faced architectural concrete.',
    notes: 'Excludes internal architectural woodwork and designer fixtures.',
    items: [
      { description: 'Underground RCC water sump tank (15,000 Litres) with crystalline waterproofing & leak test', unit: 'lumpsum', quantity: 1, rate: 185000 },
      { description: 'Anti-termite chemical soil treatment around plinth and foundation (Chlorpyrifos 20% EC)', unit: 'sq.ft.', quantity: 3200, rate: 18 },
      { description: 'Plinth filling with selected murrum in 200mm layers compacted with 8-ton vibratory roller', unit: 'brass', quantity: 45, rate: 3200 },
      { description: 'RCC M25 cantilever canopy and architectural pergola beams with form finish', unit: 'rft', quantity: 180, rate: 650 },
      { description: 'Double-wall cavity brickwork (9" + 2" cavity + 4.5") for thermal insulation on south/west elevations', unit: 'sq.ft.', quantity: 1400, rate: 240 },
      { description: 'RCC folded-plate architectural staircase casting with precision riser-tread finishing', unit: 'rft', quantity: 42, rate: 1850 },
    ],
  },
  {
    id: 'BRICK_PLASTER',
    title: 'Brick Masonry & Multi-Coat Plastering Package',
    category: 'Masonry',
    description: 'Bulk masonry and external/internal plastering contract for builders and commercial multi-storey developments.',
    defaultTaxRate: 18,
    paymentTerms: '• Weekly progressive running bill based on verified measurement sheets (JMB)\n• 10% Retention released after final curing inspection',
    termsAndConditions: '1. Sand will be river sand / washed M-sand free from silt.\n2. Minimum 7 days continuous curing for masonry and 14 days for plaster.',
    notes: 'Scaffolding charges included up to 4th floor elevation.',
    items: [
      { description: 'AAC block masonry (600x200x150mm) with polymer-modified thin-bed block adhesive', unit: 'sq.ft.', quantity: 8500, rate: 98 },
      { description: '9" Fly-ash brick masonry in cement mortar 1:6 with curing', unit: 'sq.ft.', quantity: 4500, rate: 125 },
      { description: '12mm Internal single coat cement plaster with aluminium float finish', unit: 'sq.ft.', quantity: 18000, rate: 42 },
      { description: '20mm External two-coat sand faced plaster with chicken mesh over RCC-masonry joints', unit: 'sq.ft.', quantity: 11000, rate: 68 },
      { description: 'Groove cutting and drip mould casting at chajja edges and window sills', unit: 'rft', quantity: 850, rate: 45 },
    ],
  },
  {
    id: 'FLOORING_TILING',
    title: 'Tile, Italian Marble & Granite Finishing Package',
    category: 'Finishing',
    description: 'Premium flooring, wall cladding, kitchen platforms, and diamond polishing contract.',
    defaultTaxRate: 18,
    paymentTerms: '• 30% Advance for material mobilization\n• 40% On completion of screed bed and tile laying\n• 20% After grouting and polishing\n• 10% Handover and protection removal',
    termsAndConditions: '1. Tile wastage up to 5% standard included in quotation quantity.\n2. Sub-floor cleaning and waterproofing check prior to screed bed.',
    notes: 'Paper-joint precision with zero lippage guarantee.',
    items: [
      { description: '800x1600mm Glazed vitrified tiles (GVT) laying with 2mm spacers and epoxy grout finish', unit: 'sq.ft.', quantity: 3400, rate: 185 },
      { description: 'Italian marble (Dyna / Botticino) installation over cement mortar bed with white cement slurry', unit: 'sq.ft.', quantity: 1200, rate: 450 },
      { description: 'Diamond mirror polishing for Italian marble with 7-stage abrasive discs and crystallization', unit: 'sq.ft.', quantity: 1200, rate: 120 },
      { description: '18mm Jet Black Granite kitchen platform with double moulding and sink cutout', unit: 'rft', quantity: 45, rate: 1100 },
      { description: 'Anti-skid digital ceramic tiles (300x300mm) for bathrooms and balconies with slope', unit: 'sq.ft.', quantity: 950, rate: 95 },
      { description: 'Designer glazed wall tiles up to 8ft height in bathrooms with epoxy grout', unit: 'sq.ft.', quantity: 2400, rate: 115 },
    ],
  },
  {
    id: 'WATERPROOFING',
    title: 'Comprehensive Waterproofing & Chemical Treatment',
    category: 'Waterproofing',
    description: 'Terrace, sunken toilet, basement retaining wall, and podium waterproofing with 10-year warranty.',
    defaultTaxRate: 18,
    paymentTerms: '• 25% Advance on order\n• 35% On completion of surface prep & base chemical coats\n• 30% After protective screed / brickbat coba laying\n• 10% Post 72-hour pond testing clearance',
    termsAndConditions: '1. 72-hour continuous water ponding test will be demonstrated to client engineer.\n2. 10-year stamp paper performance guarantee provided on completion.',
    notes: 'Warranty valid against water seepage with proper structural drainage maintenance.',
    items: [
      { description: 'Terrace Brick Bat Coba waterproofing (110mm avg thick) with neat cement punning and china mosaic finish', unit: 'sq.ft.', quantity: 2800, rate: 165 },
      { description: 'Two-component acrylic polymer modified elastomeric coating for sunken toilet slabs (2 coats)', unit: 'sq.ft.', quantity: 1400, rate: 85 },
      { description: 'Basement external retaining wall crystalline waterproofing membrane with protection board', unit: 'sq.ft.', quantity: 2200, rate: 135 },
      { description: 'Injection pressure grouting with non-shrink cementitious grout and PU foam at cold joints', unit: 'nos', quantity: 45, rate: 650 },
      { description: 'Construction expansion joint treatment with polysulphide sealant and backer rod', unit: 'rft', quantity: 180, rate: 320 },
    ],
  },
  {
    id: 'PAINTING_POP',
    title: 'Architectural Painting & Gypsum POP Ceiling Package',
    category: 'Finishing',
    description: 'High-end interior and exterior painting with gypsum board designer ceiling and LED cove detailing.',
    defaultTaxRate: 18,
    paymentTerms: '• 25% Mobilization advance\n• 35% On completion of POP ceiling & wall putty\n• 30% After first coat of paint throughout\n• 10% On final coat, touch-ups & cleaning',
    termsAndConditions: '1. Surface moisture meter reading below 12% before primer application.\n2. Masking tape protection on all aluminium windows, flooring, and switchboards.',
    notes: 'Asian Paints / Berger premium washable emulsion materials specified.',
    items: [
      { description: 'Saint Gobain Gyproc false ceiling with perimeter GI channels, 12.5mm boards, and tape jointing', unit: 'sq.ft.', quantity: 2400, rate: 125 },
      { description: 'Concealed LED light cove moulding and curtain drop box detailing', unit: 'rft', quantity: 380, rate: 160 },
      { description: 'Two coats of Birla White wall care putty with mechanical rotary sanding', unit: 'sq.ft.', quantity: 9800, rate: 22 },
      { description: 'Internal Royale Luxury Emulsion paint (Asian Paints) 2 coats over water-based primer', unit: 'sq.ft.', quantity: 9800, rate: 38 },
      { description: 'Exterior Apex Ultima weather-proof silicone emulsion with anti-algal protection (2 coats)', unit: 'sq.ft.', quantity: 5200, rate: 48 },
      { description: 'Synthetic enamel spray paint over red oxide primer on MS safety grills and railings', unit: 'sq.ft.', quantity: 850, rate: 42 },
    ],
  },
  {
    id: 'ROAD_PAVERS',
    title: 'Road Construction, WBM Base & Interlocking Pavers',
    category: 'Infrastructure',
    description: 'Internal township roads, factory driveways, parking zones, and heavy-duty interlocking paver block paving.',
    defaultTaxRate: 18,
    paymentTerms: '• 20% Advance\n• 40% After subgrade compaction and WBM base completion\n• 30% After paver block laying and kerb stone fixing\n• 10% On final joint sand filling and vibratory plate compaction',
    termsAndConditions: '1. Heavy-duty M40/M50 grade paver blocks tested for 40 N/mm² compressive strength.\n2. Sub-base density tested with core cutter method.',
    notes: 'Suitable for 40-ton commercial truck movement.',
    items: [
      { description: 'Subgrade earth excavation and rolling with 10-ton vibratory roller to 95% proctor density', unit: 'sq.ft.', quantity: 18000, rate: 16 },
      { description: 'Water Bound Macadam (WBM Grade II) 150mm thick base layer with stone dust binding', unit: 'sq.ft.', quantity: 18000, rate: 58 },
      { description: '80mm thick M40 grade heavy-duty interlocking paver blocks over 50mm coarse sand bedding', unit: 'sq.ft.', quantity: 16500, rate: 95 },
      { description: 'Precast M25 concrete kerb stone (450x300x150mm) bedding with 1:3:6 concrete backing and paint', unit: 'rft', quantity: 1200, rate: 340 },
      { description: 'RCC storm water road-side drainage channel (450x450mm) with heavy-duty cast iron gratings', unit: 'rft', quantity: 450, rate: 1850 },
    ],
  },
  {
    id: 'BOUNDARY_FENCING',
    title: 'Boundary Wall & Precast Security Fencing Contract',
    category: 'Civil',
    description: 'Plot perimeter protection, brick/precast boundary wall with RCC tie columns and anti-climb razor wire.',
    defaultTaxRate: 18,
    paymentTerms: '• 25% Advance\n• 40% On foundation trenching, PCC and plinth beam\n• 25% On brick superstructure and plaster\n• 10% On razor wire, coping, and paint finish',
    termsAndConditions: '1. Boundary demarcated by client with government land surveyor pins.\n2. Foundation depth calculated for black cotton soil with under-reamed piles if necessary.',
    notes: 'Perimeter security height: 7ft brickwall + 2ft razor wire = 9ft total clearance.',
    items: [
      { description: 'Trench excavation in all soils up to 1.5m depth along perimeter with backfilling', unit: 'rft', quantity: 650, rate: 180 },
      { description: 'PCC 1:4:8 bed (150mm) under boundary foundation', unit: 'rft', quantity: 650, rate: 240 },
      { description: 'RR Masonry (Random Rubble) in 1:6 mortar for foundation up to ground level', unit: 'rft', quantity: 650, rate: 580 },
      { description: 'RCC M20 plinth beam and vertical tie columns at 10ft c/c intervals', unit: 'rft', quantity: 650, rate: 420 },
      { description: '9" brick superstructure wall up to 7ft height in 1:6 cement mortar', unit: 'sq.ft.', quantity: 4550, rate: 135 },
      { description: '15mm cement plaster on both faces with weather-coat paint', unit: 'sq.ft.', quantity: 9100, rate: 58 },
      { description: 'Concertina razor wire coil (600mm dia) on Y-shape MS angle posts along top of wall', unit: 'rft', quantity: 650, rate: 290 },
    ],
  },
  {
    id: 'ELECTRICAL_PLUMBING',
    title: 'Electrical & Plumbing MEP Rough-In Contract',
    category: 'MEP Services',
    description: 'Concealed electrical conduit, wiring, sanitary drainage, water supply CPVC piping, and DB installation.',
    defaultTaxRate: 18,
    paymentTerms: '• 25% Advance\n• 35% On wall chasing, conduit and pipe laying before plaster\n• 25% On wire pulling, pressure testing, and DB dressing\n• 15% On fixture installation and electrical energization test',
    termsAndConditions: '1. Hydrostatic pressure testing of all water supply pipes at 10 kg/cm² for 24 hours.\n2. Polycab/Havells FRLS copper wires and Supreme/Astral CPVC/UPVC pipes used exclusively.',
    notes: 'Points measured as per standard IS:732 electrical code.',
    items: [
      { description: 'Concealed PVC conduit chasing with modular metal boxes in brick walls before plaster', unit: 'rft', quantity: 2400, rate: 75 },
      { description: 'Wiring for light, fan, and 6A sockets with 1.5 sq.mm & 2.5 sq.mm FRLS copper wire in conduits', unit: 'nos', quantity: 180, rate: 850 },
      { description: 'Dedicated 4.0 sq.mm circuit wiring for 1.5/2.0 Ton AC units and 25A geysers with MCB', unit: 'nos', quantity: 28, rate: 1650 },
      { description: 'CPVC concealed water distribution piping (Astral/Supreme) with brass fittings & testing', unit: 'rft', quantity: 1400, rate: 185 },
      { description: 'UPVC SWR drainage stack piping (75mm & 110mm) for sewage and rainwater with cleanouts', unit: 'rft', quantity: 680, rate: 240 },
      { description: 'Installation of 8-way TPN distribution board with RCCB and miniature circuit breakers', unit: 'nos', quantity: 4, rate: 8500 },
    ],
  },
  {
    id: 'DEMOLITION_EXCAVATION',
    title: 'Demolition, Excavation & Site Preparation Package',
    category: 'Earthwork',
    description: 'Safe demolition of existing structures, mechanized deep excavation, rock breaking, and debris removal.',
    defaultTaxRate: 18,
    paymentTerms: '• 30% Mobilization advance for heavy machinery\n• 40% On completion of structural demolition and carting\n• 30% On final foundation excavation, levelling, and site handover',
    termsAndConditions: '1. Safety barricading with GI sheets around boundary during demolition.\n2. Municipal dumping transit permits arranged by contractor.\n3. Salvageable scrap steel / doors credit adjusted against contract sum.',
    notes: '20-ton JCB/Poclain hydraulic excavators with rock breaker attachments mobilized.',
    items: [
      { description: 'Barricading site boundary with 8ft GI corrugated sheets and MS scaffolding pipes', unit: 'rft', quantity: 380, rate: 320 },
      { description: 'Demolition of existing RCC slab, beams, and columns with hydraulic rock breaker without vibration damage to adjacent plots', unit: 'sq.ft.', quantity: 3200, rate: 110 },
      { description: 'Demolition of brick and stone masonry walls with mechanical excavator', unit: 'cum', quantity: 250, rate: 450 },
      { description: 'Loading and transportation of demolition debris and concrete malba to municipal landfill', unit: 'brass', quantity: 65, rate: 2800 },
      { description: 'Bulk basement excavation in hard soil/rock up to 4.5m depth with slope protection', unit: 'cum', quantity: 1800, rate: 320 },
      { description: 'Laser-guided grading, surface levelling, and 12-ton compaction for foundation base', unit: 'sq.ft.', quantity: 7500, rate: 12 },
    ],
  },
  {
    id: 'RENOVATION_REMODELING',
    title: 'Building Renovation & Structural Remodeling Contract',
    category: 'Renovation',
    description: 'Modernization of existing residential/commercial properties: structural strengthening, floor replacement, and facade upgrade.',
    defaultTaxRate: 18,
    paymentTerms: '• 25% Advance on agreement\n• 30% On completion of dismantling and structural retrofitting\n• 30% On tile laying, plumbing, and plastering\n• 15% On painting, fixtures, and final handover',
    termsAndConditions: '1. Protection of existing non-renovated areas with plastic sheeting and hardboard.\n2. Structural engineer verification for any load-bearing wall opening.',
    notes: 'Turnaround duration: 45 calendar days from site possession.',
    items: [
      { description: 'Chipping and removal of existing damaged floor tiles and 50mm screed bed', unit: 'sq.ft.', quantity: 1800, rate: 45 },
      { description: 'Wall opening creation with RCC precast lintel insertion for double-door entrance', unit: 'nos', quantity: 3, rate: 14500 },
      { description: 'Structural carbon fiber wrap / micro-concrete jacket strengthening for distressed columns', unit: 'nos', quantity: 6, rate: 22000 },
      { description: 'Replacing corroded GI plumbing lines with external CPVC open chase lines with clamps', unit: 'rft', quantity: 350, rate: 220 },
      { description: 'Re-plastering chipped areas with polymer-modified bonding agent (SBR latex)', unit: 'sq.ft.', quantity: 2400, rate: 65 },
      { description: 'Installing premium 600x1200mm vitrified tiles over existing floor with high-bond adhesive', unit: 'sq.ft.', quantity: 1800, rate: 175 },
    ],
  },
  {
    id: 'STEEL_FABRICATION',
    title: 'Industrial PEB Steel Shed & Roofing Fabrication',
    category: 'Fabrication',
    description: 'Design, fabrication, and erection of Pre-Engineered Building (PEB) warehouse shed with Galvalume roofing.',
    defaultTaxRate: 18,
    paymentTerms: '• 30% Advance for raw steel procurement\n• 30% On shop fabrication inspection and primer painting\n• 25% On delivery and erection of structural frames at site\n• 15% On roof sheeting, accessories, and watertight testing',
    termsAndConditions: '1. Structural steel conforms to IS 2062 Grade E250 / E350.\n2. Roofing sheets 0.50mm BMT Galvalume with AZ150 zinc-aluminium coating.\n3. Crane for steel erection arranged by contractor.',
    notes: 'Wind speed designed for 47 m/sec as per IS 875 Part 3.',
    items: [
      { description: 'Anchor bolt casting in concrete pedestals with template alignment', unit: 'nos', quantity: 24, rate: 2400 },
      { description: 'Fabrication and erection of built-up I-section steel columns and rafters including welding, zinc chromate primer, and 2 coats epoxy paint', unit: 'ton', quantity: 18, rate: 98000 },
      { description: 'Cold-formed high-tensile Z & C purlins (200mm depth, 2.0mm thick) with sag rods and bracing', unit: 'ton', quantity: 6, rate: 105000 },
      { description: '0.50mm TCT Pre-painted Galvalume trapezoidal profile roof sheeting with self-drilling fasteners and EPDM washers', unit: 'sq.ft.', quantity: 8500, rate: 92 },
      { description: '0.50mm Galvalume wall cladding sheets with flashing and trim details', unit: 'sq.ft.', quantity: 4200, rate: 88 },
      { description: 'Ridge vents, gutters, and downspout pipes (160mm PVC) with rainwater discharge', unit: 'rft', quantity: 320, rate: 450 },
      { description: 'Roof wind-driven turbo ventilators (24" stainless steel) for natural industrial air circulation', unit: 'nos', quantity: 8, rate: 7500 },
    ],
  },
];
